version: "3.9"

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: allthebeansdb
    ports:
      - "3306:3306" # Expose MySQL on the default port
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: