// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using all_the_beans.Data.Context;

#nullable disable

namespace all_the_beans.Data.Migrations
{
    [DbContext(typeof(CoffeeBeanDbContext))]
    [Migration("20250506180644_AddLastBeanOfTheDayColumnAndIndex")]
    partial class AddLastBeanOfTheDayColumnAndIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("all_the_beans.Data.Tables.CoffeeBeanTable.CoffeeBeanTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(24)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Index"));

                    b.Property<bool>("IsBeanOfTheDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("LastBeanOfTheDayTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Colour");

                    b.HasIndex("Country");

                    b.HasIndex("Index")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("CoffeeBean");
                });
#pragma warning restore 612, 618
        }
    }
}
