name: Build and Test .NET Project

on:
  push:
  # Trigger on push to master branch
    branches: [ "master" ]
  pull_request:
  # Trigger on pull request targeting master branch
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution - Ensures no build failures
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests (including .feature scenarios)
      # Skips build as Step 4. covers this
      - name: Run tests
        run: dotnet test --no-build --configuration Release"